# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel-app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
            - traefik
        depends_on:
            - mysql
            - redis
            - selenium
        labels:
          - "traefik.enable=true"
          - "traefik.docker.network=traefik"
          - "traefik.http.routers.laravel-app.entrypoints=http"
          - "traefik.http.routers.laravel-app.rule=Host(`${APP_HOST}`) || Host(`www.${APP_HOST}`)"
          - "traefik.http.middlewares.laravel-app-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.laravel-app.middlewares=laravel-app-https-redirect"

          - "traefik.http.routers.laravel-app-secure.entrypoints=https"
          - "traefik.http.routers.laravel-app-secure.rule=Host(`${APP_HOST}`) || Host(`www.${APP_HOST}`)"
          - "traefik.http.routers.laravel-app-secure.tls=true"
          - "traefik.http.routers.laravel-app-secure.tls.certresolver=letsEncrypt"
          - "traefik.http.routers.laravel-app-secure.service=laravel-app"
          - "traefik.http.services.laravel-app.loadbalancer.server.port=${APP_PORT}"
    mysql:
        image: 'mysql:8.0'
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - sail
    mailhog:
        image: 'mailhog/mailhog:latest'
        networks:
            - sail
    selenium:
       image: 'selenium/standalone-chrome'
       volumes:
            - '/dev/shm:/dev/shm'
       networks:
           - sail
networks:
    sail:
        driver: bridge
    traefik:
        external: true
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local
