# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel-app:
        ports:
            - '${APP_PORT:-80}:80'
        labels:
          - "traefik.enable=false"
    mysql:
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
    redis:
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
    meilisearch:
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
    selenium:
       image: 'selenium/standalone-chrome'
       volumes:
            - '/dev/shm:/dev/shm'
       networks:
           - sail
networks:
  traefik:
    external: false
    driver: bridge
